apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-account-configmap
  namespace: internet-banking
data:
  FLASK_APP: app/__init__.py
  FLASK_ENV: development
  DATABASE_URL: postgresql://root:secret@postgres-svc:5432/internet_banking
  SQL_HOST: postgres-svc
  SQL_PORT: "5432"
  SECRET_KEY: "Q7KAuYeP8NC5"