apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
  namespace: internet-banking
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    rule_files:
    scrape_configs:
      - job_name: 'user'
        dns_sd_configs:
          - names: ['user-svc']
            port: 5001
            type: A
            refresh_interval: 5s
      - job_name: 'bank-account'
        dns_sd_configs:
          - names: ['bank-account-svc']
            port: 5002
            type: A
            refresh_interval: 5s
