apiVersion: v1
kind: Service
metadata:
  name: bank-account-svc
  labels:
    app: bank-account
spec:
  type: ClusterIP
  selector:
    app: bank-account
  ports:
    - port: 5002
      targetPort: 5002