
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: internet-banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgredb"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - image: postgres:12-alpine
        imagePullPolicy: Always
        name: postgresdb
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-configmap
        readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
        livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 20
