apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: internet-banking
spec:
  type: ClusterIP
  ports:
  - name: "port"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres

