apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: evertonalaauk/user:1.0.2
          command: ["gunicorn", "--bind", "0.0.0.0:5001", "manage:app"]
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: user-configmap