version: '3.7'
services:
  user:
    #image: evertonalaauk/user:1.0.1
    build: ./user
    command: gunicorn --bind 0.0.0.0:5001 manage:app
    restart: always
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://root:secret@psql_db:5432/internet_banking
      - SQL_HOST=psql_db
      - SQL_PORT=5432
      - SECRET_KEY=Q7KAuYeP8NC5
    ports:
      - 5001:5001
    depends_on:
      - psql_db
      - prometheus
      - grafana
    networks:
      - internet_banking_network
    volumes:
      - ./user/:/usr/src/app
    container_name: user
  bank_account:
    #image: evertonalaauk/bank_account:1.0.1
    build: ./bank_account
    command: gunicorn --bind 0.0.0.0:5002 manage:app
    restart: always
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://root:secret@psql_db:5432/internet_banking
      - SQL_HOST=psql_db
      - SQL_PORT=5432
      - SECRET_KEY=Q7KAuYeP8NC5
    ports:
      - 5002:5002
    depends_on:
      - psql_db
      - prometheus
      - grafana
    networks:
      - internet_banking_network
    volumes:
      - ./bank_account/:/usr/src/app
    container_name: bank_account
  psql_db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=internet_banking
    networks:
      - internet_banking_network
    container_name: postgres
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - internet_banking_network
    container_name: prometheus
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=user@gmail.com
      - GF_SECURITY_ADMIN_PASSWORD=secret
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
    networks:
      - internet_banking_network
    container_name: grafana
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root # secret
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    container_name: jenkins
networks:
  internet_banking_network:
    name: internet-banking-network
    driver: bridge
volumes:
  postgres_data:
  prometheus:
  jenkins:
